language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - feature/pin2dmd

before_script:
  - pip install --user codecov

after_success:
  - codecov

install: "mvn install -Plinux_x86_64 -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "mvn -Plinux_x86_64 clean package assembly:single"
