language: java

jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
after_success:
  - codecov

install: "mvn install -Plinux_x86_64 -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

script: "mvn -Plinux_x86_64 clean package assembly:single"
